### ISSUE TITLE
Assorted problems in RRVL

### ISSUE THREAD

**Issue by DrBuns3n** [valadaa48/retroroller#178] opened 2020-08-31 18:28 UTC
flycast 64 bit: failed to open libretro core

no spring launcher for retrorun flycast32

mupen64plus-next: failed to open libretro core

spring mupen64plus quits back to RA (is this supposed to be the retrorun spring?)

start+select to quit to RA hotkeys do not work in Stella 2014 and Prosystem 

spring Drastic quits back to RA

**Comment by mariovirgili** [comment] 2020-08-31 19:01
To fix some problems: sudo ln -s /usr/lib/mali/libGLESv2.so /usr/lib/libGLESv2.so

**Comment by DrBuns3n** [comment] 2020-08-31 20:10
[odroid@rrvl ~]$ sudo ln -s /usr/lib/mali/libGLESv2.so /usr/lib/libGLESv2.so
ln: failed to create symbolic link '/usr/lib/libGLESv2.so': File exists

Received the above error trying to apply the fix.

**Comment by DrBuns3n** [comment] 2020-08-31 20:26
After applying sudo ln -s /usr/lib/mali/libGLESv2.so /usr/lib/libGLESv2.so, the following now works:
- flycast 64 bit
- spring mupen64plus

**Comment by valadaa48** [comment] 2020-09-01 01:12
I reproduced this libGLESv2.so issue, it was caused by rockchip's new drivers. I'll be rolling these back soon.

**Comment by valadaa48** [comment] 2020-09-01 03:18
> flycast 64 bit: failed to open libretro core

this is fixed in latest RRVL

> no spring launcher for retrorun flycast32

Please create a separate issue to track adding retrorun

> mupen64plus-next: failed to open libretro core

This should work now

> spring mupen64plus quits back to RA (is this supposed to be the retrorun spring?)

This should launch the standalone mupen64plus and I confirmed it works in the new update

start+select to quit to RA hotkeys do not work in Stella 2014 and Prosystem

> I think F1+F2 are the hotkeys, not start+select

spring Drastic quits back to RA

> This is tested as working in the latest update

**Closed by valadaa48** 2020-09-01 03:18 UTC

**Comment by valadaa48** [comment] 2020-09-01 04:09
retrorun and retrorun32 were added as packages in the next update.
