### ISSUE TITLE
RL2 not closing when launching EE-ES

### ISSUE THREAD

**Issue by tlayne** [valadaa48/retroroller#65] opened 2020-05-27 23:22 UTC
If your device boots to RL2.0 and you launch Emuelec EmulationStation the RL 2.0 screen pops up every time you load a game. The user is also returned to RL 2.0 when waking from sleep.

**Comment by valadaa48** [comment] 2020-05-28 13:33
can someone else confirm this issue? I can't reproduce

**Comment by npaladin2000** [comment] 2020-05-28 13:50
The first part of the issue I can confirm, but not the second part, it's sending me back to ES.

**Comment by tlayne** [comment] 2020-05-28 19:07
I just updated to latest and this is still an issue on both fronts for me. Hopefully others can let us know if it is local or an issue for everyone.

**Comment by valadaa48** [comment] 2020-05-29 03:10
this should be fixed

**Closed by valadaa48** 2020-05-29 03:10 UTC
Labels: can't reproduce
