### ISSUE TITLE
black screen issue

### ISSUE THREAD

**Issue by dj5928** [valadaa48/retroroller#203] opened 2021-02-02 18:38 UTC
Sometimes during gameplay
The screen turns off for no reason.
The sound and game will continue and only the screen will turn black.
The screen is displayed again only after entering the sleep mode.

**Comment by valadaa48** [comment] 2021-02-03 02:24
This is on OGS?

**Comment by valadaa48** [comment] 2021-02-03 02:25
duplicate of #197

**Closed** 2021-02-03 02:25 UTC
Labels: duplicate
