### ISSUE TITLE
Restart Emulation Station quits back to RS2

### ISSUE THREAD

**Issue by DrBuns3n** [valadaa48/retroroller#87] opened 2020-05-31 19:12 UTC
In the EmuElec version of Emulation Station, the Quit/Restart Emulation Station menu option quits back to RetroLauncher2 instead of restarting emulation station.

**Comment by valadaa48** [comment] 2020-05-31 20:00
This is by design until someone ports a wrapper script to emuelec-es. Restart worked by quitting then touching a file in /tmp then the wrapper script would reload it. EE currently is set to always restart in systemd so if it's your default launcher then quit/restart will restart back into ES. If you use RL2 then EE will quit back to RL2. I think this is a minor annoyance but documenting here if someone can write and test a wrapper script.

**Comment by valadaa48** [comment] 2020-06-06 13:42
this is fixed in the latest version

**Closed by valadaa48** 2020-06-06 13:42 UTC
Labels: help wanted
