### ISSUE TITLE
Drastic menu unresponsive (Void)

### ISSUE THREAD

**Issue by shoesio** [valadaa48/retroroller#149] opened 2020-07-03 23:11 UTC
Latest update of Drastic introduces bug that makes menu in Drastic not display every button press. Only every third press is updated onscreen, although first and second presses are processed.

To reproduce: Press F1 to enter menu.
Use Pad to move between menu options, only one in three presses are updated onscreen.

**Comment by valadaa48** [comment] 2020-07-03 23:35
I can't reproduce. Can anyone else?

**Comment by SeongGino** [comment] 2020-07-08 13:31
I'm not sure if this counts as 'reproduce' but it's affecting me here too.

Also the framerate is dramatically reduced, even at points where it should be running fine without frameskip.

**Comment by valadaa48** [comment] 2020-07-09 04:27
Can you try changing /usr/bin/drastic to:

```
#!/bin/sh

cd /opt/drastic
LD_PRELOAD=/usr/lib/libSDL2-2.0.so.0.10.0 /drastic "$@"
```

and see if it helps?

**Comment by SeongGino** [comment] 2020-07-09 15:58
That does seem to fix the problem.

**Comment by valadaa48** [comment] 2020-07-09 16:47
OK thanks for confirming. I guess there a few things we can do here:

1) Force 2.0.10 system-wide and get rid of 2.0.12 completely. I think EmuELEC does this.
2) All SDL2 apps that have this issue needs to have a bash script to do the LD_PRELOAD dance.

Any thoughts?

**Comment by shoesio** [comment] 2020-07-09 18:26
Menu issue seems fixed, but showing new issues in emu now. Experienced a crash, slower performance and some kind of flashing / black frame insertion.

**Comment by valadaa48** [comment] 2020-07-09 18:48
does this happen in EE?

**Comment by shoesio** [comment] 2020-07-09 18:58
No, menu reacts fine

**Comment by SeongGino** [comment] 2020-07-09 21:02
> 
> 
> Menu issue seems fixed, but showing new issues in emu now. Experienced a crash, slower performance and some kind of flashing / black frame insertion after frame skip being applied

Can't reproduce, and performance difference is difficult to gauge when the original performance pre-fix felt as if it was layered beneath four degrees of Frameskip.

**Comment by shoesio** [comment] 2020-07-09 21:04
Just testing some more now, performance in game is very variable, moves from silky smooth to half speed with nothing on screen particularly causing it.

**Comment by shoesio** [comment] 2020-07-09 21:34
I think the black frame thing was my battery dying to be honest. Having played a good half hour on it I haven't noticed that again. Performance is still variable in normal play however.

**Comment by valadaa48** [comment] 2020-07-10 19:29
are you running in performance mode?

**Comment by shoesio** [comment] 2020-07-10 19:32
The spring should ensure that right?

**Comment by valadaa48** [comment] 2020-07-15 00:52
try updated and ensure SDL2-2.0.10-go2 is removed and SDL2-go2 is downgraded to 2.0.10. I tested it and can't reproduce now.

**Comment by SeongGino** [comment] 2020-07-15 01:17
Updated, also can't reproduce.

**Comment by valadaa48** [comment] 2020-07-15 03:24
Thanks, let's close this for now as I think we got it.

**Closed by valadaa48** 2020-07-15 03:24 UTC
